export * from './IconAdd'
export * from './IconCorrect'
export * from './IconEmojiPeople'
export * from './IconFace'
export * from './IconGift'
export * from './IconIncorrect'
export * from './IconLoading'
export * from './IconPencil'
